"""Оформление отчётных Excel-файлов VOC."""

HEADER_COLOR = "1F4E79"
BLOCK_COLOR = "DCE6F1"
TOTAL_COLOR = "FFF2CC"
VIOLATION_COLOR = "C00000"

CATEGORY_WIDTH = 42
ITEM_WIDTH = 95
RESTAURANT_WIDTH = 7
TOTAL_WIDTH = 14
